//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPositionServo
{
    [Serializable]
    public class EndPointStateMsg : Message
    {
        public const string k_RosMessageName = "franka_position_servo/EndPointState";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double[] O_T_EE;
        //  Measured end effector pose in base frame
        //  ----- Moved ee velocity to robot state, because it is being computed using J*dq. EE vel is not being provided natively
        // float64[6] O_dP_EE_c # Last commanded end effector twist in base frame.
        // float64[6] O_dP_EE_d # Desired end effector twist in base frame.
        // float64[6] O_ddP_EE_c # Last commanded end effector acceleration in base frame.
        public Geometry.WrenchStampedMsg O_F_ext_hat_K;
        //  Estimated external wrench (force, torque) acting on stiffness frame, expressed relative to the base frame
        public Geometry.WrenchStampedMsg K_F_ext_hat_K;
        //  Estimated external wrench (force, torque) acting on stiffness frame, expressed relative to the stiffness frame (ee_frame by default)

        public EndPointStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.O_T_EE = new double[16];
            this.O_F_ext_hat_K = new Geometry.WrenchStampedMsg();
            this.K_F_ext_hat_K = new Geometry.WrenchStampedMsg();
        }

        public EndPointStateMsg(Std.HeaderMsg header, double[] O_T_EE, Geometry.WrenchStampedMsg O_F_ext_hat_K, Geometry.WrenchStampedMsg K_F_ext_hat_K)
        {
            this.header = header;
            this.O_T_EE = O_T_EE;
            this.O_F_ext_hat_K = O_F_ext_hat_K;
            this.K_F_ext_hat_K = K_F_ext_hat_K;
        }

        public static EndPointStateMsg Deserialize(MessageDeserializer deserializer) => new EndPointStateMsg(deserializer);

        private EndPointStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.O_T_EE, sizeof(double), 16);
            this.O_F_ext_hat_K = Geometry.WrenchStampedMsg.Deserialize(deserializer);
            this.K_F_ext_hat_K = Geometry.WrenchStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.O_T_EE);
            serializer.Write(this.O_F_ext_hat_K);
            serializer.Write(this.K_F_ext_hat_K);
        }

        public override string ToString()
        {
            return "EndPointStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nO_T_EE: " + System.String.Join(", ", O_T_EE.ToList()) +
            "\nO_F_ext_hat_K: " + O_F_ext_hat_K.ToString() +
            "\nK_F_ext_hat_K: " + K_F_ext_hat_K.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
