//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class MecanumDriveControllerStateMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/MecanumDriveControllerState";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double front_left_wheel_velocity;
        public double back_left_wheel_velocity;
        public double back_right_wheel_velocity;
        public double front_right_wheel_velocity;
        public Geometry.TwistMsg reference_velocity;

        public MecanumDriveControllerStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.front_left_wheel_velocity = 0.0;
            this.back_left_wheel_velocity = 0.0;
            this.back_right_wheel_velocity = 0.0;
            this.front_right_wheel_velocity = 0.0;
            this.reference_velocity = new Geometry.TwistMsg();
        }

        public MecanumDriveControllerStateMsg(Std.HeaderMsg header, double front_left_wheel_velocity, double back_left_wheel_velocity, double back_right_wheel_velocity, double front_right_wheel_velocity, Geometry.TwistMsg reference_velocity)
        {
            this.header = header;
            this.front_left_wheel_velocity = front_left_wheel_velocity;
            this.back_left_wheel_velocity = back_left_wheel_velocity;
            this.back_right_wheel_velocity = back_right_wheel_velocity;
            this.front_right_wheel_velocity = front_right_wheel_velocity;
            this.reference_velocity = reference_velocity;
        }

        public static MecanumDriveControllerStateMsg Deserialize(MessageDeserializer deserializer) => new MecanumDriveControllerStateMsg(deserializer);

        private MecanumDriveControllerStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.front_left_wheel_velocity);
            deserializer.Read(out this.back_left_wheel_velocity);
            deserializer.Read(out this.back_right_wheel_velocity);
            deserializer.Read(out this.front_right_wheel_velocity);
            this.reference_velocity = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.front_left_wheel_velocity);
            serializer.Write(this.back_left_wheel_velocity);
            serializer.Write(this.back_right_wheel_velocity);
            serializer.Write(this.front_right_wheel_velocity);
            serializer.Write(this.reference_velocity);
        }

        public override string ToString()
        {
            return "MecanumDriveControllerStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nfront_left_wheel_velocity: " + front_left_wheel_velocity.ToString() +
            "\nback_left_wheel_velocity: " + back_left_wheel_velocity.ToString() +
            "\nback_right_wheel_velocity: " + back_right_wheel_velocity.ToString() +
            "\nfront_right_wheel_velocity: " + front_right_wheel_velocity.ToString() +
            "\nreference_velocity: " + reference_velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
