//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaGripper
{
    [Serializable]
    public class GraspGoalMsg : Message
    {
        public const string k_RosMessageName = "franka_gripper/GraspGoal";
        public override string RosMessageName => k_RosMessageName;

        public double width;
        public GraspEpsilonMsg epsilon;
        public double speed;
        public double force;

        public GraspGoalMsg()
        {
            this.width = 0.0;
            this.epsilon = new GraspEpsilonMsg();
            this.speed = 0.0;
            this.force = 0.0;
        }

        public GraspGoalMsg(double width, GraspEpsilonMsg epsilon, double speed, double force)
        {
            this.width = width;
            this.epsilon = epsilon;
            this.speed = speed;
            this.force = force;
        }

        public static GraspGoalMsg Deserialize(MessageDeserializer deserializer) => new GraspGoalMsg(deserializer);

        private GraspGoalMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.width);
            this.epsilon = GraspEpsilonMsg.Deserialize(deserializer);
            deserializer.Read(out this.speed);
            deserializer.Read(out this.force);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.width);
            serializer.Write(this.epsilon);
            serializer.Write(this.speed);
            serializer.Write(this.force);
        }

        public override string ToString()
        {
            return "GraspGoalMsg: " +
            "\nwidth: " + width.ToString() +
            "\nepsilon: " + epsilon.ToString() +
            "\nspeed: " + speed.ToString() +
            "\nforce: " + force.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
