//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaGripper
{
    [Serializable]
    public class GraspActionGoalMsg : Message
    {
        public const string k_RosMessageName = "franka_gripper/GraspActionGoal";
        public override string RosMessageName => k_RosMessageName;

        public GraspGoalMsg goal;

        public GraspActionGoalMsg()
        {
            this.goal = new GraspGoalMsg();
        }

        public GraspActionGoalMsg(GraspGoalMsg goal)
        {
            this.goal = goal;
        }

        public static GraspActionGoalMsg Deserialize(MessageDeserializer deserializer) => new GraspActionGoalMsg(deserializer);

        private GraspActionGoalMsg(MessageDeserializer deserializer)
        {
            this.goal = GraspGoalMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "GraspActionGoalMsg: " +
            "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
