//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaGripper
{
    [Serializable]
    public class MoveGoalMsg : Message
    {
        public const string k_RosMessageName = "franka_gripper/MoveGoal";
        public override string RosMessageName => k_RosMessageName;

        public double width;
        public double speed;

        public MoveGoalMsg()
        {
            this.width = 0.0;
            this.speed = 0.0;
        }

        public MoveGoalMsg(double width, double speed)
        {
            this.width = width;
            this.speed = speed;
        }

        public static MoveGoalMsg Deserialize(MessageDeserializer deserializer) => new MoveGoalMsg(deserializer);

        private MoveGoalMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.width);
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.width);
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "MoveGoalMsg: " +
            "\nwidth: " + width.ToString() +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
