//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaGripper
{
    [Serializable]
    public class MoveActionGoalMsg : Message
    {
        public const string k_RosMessageName = "franka_gripper/MoveActionGoal";
        public override string RosMessageName => k_RosMessageName;

        public MoveGoalMsg goal;

        public MoveActionGoalMsg()
        {
            this.goal = new MoveGoalMsg();
        }

        public MoveActionGoalMsg(MoveGoalMsg goal)
        {
            this.goal = goal;
        }

        public static MoveActionGoalMsg Deserialize(MessageDeserializer deserializer) => new MoveActionGoalMsg(deserializer);

        private MoveActionGoalMsg(MessageDeserializer deserializer)
        {
            this.goal = MoveGoalMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "MoveActionGoalMsg: " +
            "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
