# global robot configuration and details

robot_config:
    joint_names:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    arm_id: fr3
        # Activate rate limiter? [true|false]
    rate_limiting: true
    # Cutoff frequency of the low-pass filter. Set to >= 1000 to deactivate.
    cutoff_frequency: 100
    # Internal controller for motion generators [joint_impedance|cartesian_impedance]
    internal_controller: joint_impedance

    neutral_pose:
        fr3_joint1: -0.017792060227770554 
        fr3_joint2: -0.7601235411041661  
        fr3_joint3: 0.019782607023391807 
        fr3_joint4: -2.342050140544315 
        fr3_joint5: 0.029840531355804868 
        fr3_joint6: 1.5411935298621688 
        fr3_joint7: 0.7534486589746342 

    joint_config:
        joint_acceleration_limit:
            fr3_joint1: 15.0 # rad / sec^2
            fr3_joint2: 7.5  # rad / sec^2
            fr3_joint3: 10.0 # rad / sec^2
            fr3_joint4: 12.5 # rad / sec^2
            fr3_joint5: 15.0 # rad / sec^2
            fr3_joint6: 20.0 # rad / sec^2
            fr3_joint7: 20.0 # rad / sec^2
            # fr3_finger_joint1: 12.0 # rad / sec^2
            # fr3_finger_joint2: 12.0 # rad / sec^2

        joint_velocity_limit:
            fr3_joint1: 2.1750 # rad / sec
            fr3_joint2: 2.1750 # rad / sec
            fr3_joint3: 2.1750 # rad / sec
            fr3_joint4: 2.1750 # rad / sec
            fr3_joint5: 2.6100 # rad / sec
            fr3_joint6: 2.6100 # rad / sec
            fr3_joint7: 2.6100 # rad / sec
            # fr3_finger_joint1: 2.0 # rad / sec
            # fr3_finger_joint2: 2.0 # rad / sec

        joint_position_limit:
            lower: 
                fr3_joint1: -2.8973 # rad
                fr3_joint2: -1.7628 # rad
                fr3_joint3: -2.8973 # rad
                fr3_joint4: -3.0718 # rad
                fr3_joint5: -2.8973 # rad
                fr3_joint6: -0.0175 # rad
                fr3_joint7: -2.8973 # rad
            upper:
                fr3_joint1: 2.8973 # rad
                fr3_joint2: 1.7628 # rad
                fr3_joint3: 2.8973 # rad
                fr3_joint4: -0.0698 # rad
                fr3_joint5: 2.8973 # rad
                fr3_joint6: 3.7525 # rad
                fr3_joint7: 2.8973 # rad

        joint_effort_limit:
            fr3_joint1: 87 # Nm
            fr3_joint2: 87 # Nm
            fr3_joint3: 87 # Nm
            fr3_joint4: 87 # Nm
            fr3_joint5: 12 # Nm
            fr3_joint6: 12 # Nm
            fr3_joint7: 12 # Nm            

gripper_config:
  joint_names:
    - fr3_finger_joint1
    - fr3_finger_joint2
  default_speed: 0.1  # [m/s]
  default_grasp_epsilon:
    inner: 0.005 # [m]
    outer: 0.005 # [m]

controllers_config:
    position_controller: "franka_position_servo/joint_position_controller"
    trajectory_controller: "position_joint_trajectory_controller"
